version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cdac-mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cdac-network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  cdac-network:
    driver: bridge
